version: 2

jobs:

  # # python2:
  # build:
  #   working_directory: ~/orthopy
  #   docker:
  #     - image: ubuntu:17.10
  #   steps:
  #     - run: apt-get update
  #     - run: apt-get install -y git python-pip
  #     - run: pip2 install -U pytest pytest-cov pylint
  #     - checkout
  #     - run: pip2 install .
  #     # lint
  #     - run: pylint orthopy/
  #     - run: pylint test/*.py
  #     # The tests
  #     - run: cd test/ && MPLBACKEND=Agg pytest --cov orthopy
  #     # submit to codecov
  #     - run: apt-get install -y curl
  #     - run: bash <(curl -s https://codecov.io/bash)

  # python3:
  build:
    working_directory: ~/orthopy
    docker:
      - image: ubuntu:17.10
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: pip3 install .[sphere-plot,disk-plot]
      - run: pip3 install -r test_requirements.txt
      # lint
      - run: pylint orthopy/
      - run: pylint test/*.py
      # The tests
      - run: cd test/ && MPLBACKEND=Agg pytest --cov orthopy
      # submit to codecov
      - run: apt-get install -y curl
      - run: bash <(curl -s https://codecov.io/bash)

# workflow builds don't support forked PRs yet, cf.
# <https://circleci.com/docs/2.0/faq/#can-i-build-fork-prs-using-workflows>.
# workflows:
#   version: 2
#   build-and-test:
#     jobs:
#       - python2
#       - python3
